services:
  mongo:
    image: mongo:5
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:6
    container_name: redis_cache
    ports:
      - "6379:6379"

  users:
    build:
      context: .
      dockerfile: services/users/Dockerfile
    container_name: users_service
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
    env_file: .env
    depends_on:
      - mongo
      - redis

  items:
    build:
      context: .
      dockerfile: services/items/Dockerfile
    container_name: items_service
    ports:
      - "4002:4002"
    env_file: .env
    depends_on:
      - mongo
      - redis

  orders:
    build:
      context: .
      dockerfile: services/orders/Dockerfile
    container_name: orders_service
    ports:
      - "4003:4003"
    environment:
      - PORT=4003
    env_file: .env
    depends_on:
      - mongo
      - redis

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: auth_service
    ports:
      - "4004:4004"
    environment:
      - PORT=4004
    env_file: .env
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - users
      - items
      - orders
      - auth

volumes:
  mongo_data:
